### PR TITLE
NEW: updates Decimal dependency to allow for v2.0

### PR DESCRIPTION
**Pull request by glennr**
Fixes dependency issues when your project relies on Decimal 2.x but PgRanges forces a downgrade to ~> 1.9

AFAICT from searching the code PgRanges doesn't break if you upgrade to `decimal@2.0`. I did see a warning on the deprecated `cmp` function, but that was in a dependency, not in this lib. 

NOTE: I verified it on my project but I didn't add an automated regression test for it in this project. I'm guessing we'd have to somehow lock the mix version to Decimal v1.x, invoke mix test, and rinse and repeat with Decimal 2.x?

### CODE REVIEW

**Comment by eaguilera23** [comment]
Hi guys. Do we need something else to merge this PR?

**Comment by davidarnold** [comment]
Politely bumping this request 🙏

**Comment by lennartschoch** [comment]
Would love to see this merged too :)

**Comment by davidarnold** [comment]
I waited a year to follow up, so I hope I'm not being too _pushy_ but can we move this forward?  Does the project lack an active maintainer at the moment?

CC: @vforgione @rparcus

**Comment by vforgione** [comment]
Sorry, I've been away from this for a really long time. I've merged another more recent PR (https://github.com/vforgione/pg_ranges/pull/13) that covers this and pushed a new release to hex.

**Pull request closed without merging**
